### ISSUE TITLE
Funds stuck in pancake swap liquidity pool

### ISSUE THREAD

**Issue by gregjarrett** [Safemoon-Protocol/safemoon.sol#7]
I created a copy of this contract from bscscan and published it with a new name using remix 6.12 compiler version.
Seems to work on my test version seemed to also work fine in the liquidity pool.  However the final release version seem to be stuck in the liquidity pool, the tokens and liquidity LP appear.  However the tokens are not tradeable and the pool is not withdrawable despite 100% of liquidity owned.    I put 100% of the minted tokens + a few BNB into the pool initially seems to be slightly stuck.  I'm unsure what is causing this issue any ideas or suggestions to unstick this problem?

**Comment by gregjarrett** [comment]
Bug fixed was a router issue

**Comment by Jovonni** [comment]
> Bug fixed was a router issue

Can you elaborate on the router issue you observed? Might help the community

**Comment by gregjarrett** [comment]
Yes, the problem was the contract hard coded in pancakeswap v1 router. When adding a pool to v2 the contract stalled at certain points the only solution was to turn the liquify variable to false to unlock it. However the correct course of action is to use the v2 router address!
